// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7px-T9Gclh1gSrsNOhjz7dVw1_QzsyoI',
    appId: '1:367791406144:web:965732fad1dfed09bf33a5',
    messagingSenderId: '367791406144',
    projectId: 'open-square',
    authDomain: 'open-square.firebaseapp.com',
    databaseURL: 'https://open-square-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'open-square.firebasestorage.app',
    measurementId: 'G-D4PHV5VW1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8f5FnxLKPr_PC_H3trUliI8TesIj_wyc',
    appId: '1:367791406144:android:d56742b64e0b9a5ebf33a5',
    messagingSenderId: '367791406144',
    projectId: 'open-square',
    databaseURL: 'https://open-square-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'open-square.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7nhECMJkS5ZGm5SfjJD8iGwTGx3tAJd0',
    appId: '1:367791406144:ios:2c7493b3ad4b7472bf33a5',
    messagingSenderId: '367791406144',
    projectId: 'open-square',
    databaseURL: 'https://open-square-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'open-square.firebasestorage.app',
    iosBundleId: 'com.example.openSquare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7nhECMJkS5ZGm5SfjJD8iGwTGx3tAJd0',
    appId: '1:367791406144:ios:2c7493b3ad4b7472bf33a5',
    messagingSenderId: '367791406144',
    projectId: 'open-square',
    databaseURL: 'https://open-square-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'open-square.firebasestorage.app',
    iosBundleId: 'com.example.openSquare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7px-T9Gclh1gSrsNOhjz7dVw1_QzsyoI',
    appId: '1:367791406144:web:3df2a98c18b71d41bf33a5',
    messagingSenderId: '367791406144',
    projectId: 'open-square',
    authDomain: 'open-square.firebaseapp.com',
    databaseURL: 'https://open-square-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'open-square.firebasestorage.app',
    measurementId: 'G-PTK4CKR6V5',
  );

}