// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64QDqucsuqsqV8zz7GyyO1SGruwSNEBE',
    appId: '1:953606872243:web:370cfa9882ed512d7524c6',
    messagingSenderId: '953606872243',
    projectId: 'ccclone-1e594',
    authDomain: 'ccclone-1e594.firebaseapp.com',
    databaseURL: 'https://ccclone-1e594-default-rtdb.firebaseio.com',
    storageBucket: 'ccclone-1e594.firebasestorage.app',
    measurementId: 'G-GQETT19ZP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGLeABnxoW8AChICeR52SIrCD_lZgXC8',
    appId: '1:953606872243:android:6c89475cc0dab17b7524c6',
    messagingSenderId: '953606872243',
    projectId: 'ccclone-1e594',
    databaseURL: 'https://ccclone-1e594-default-rtdb.firebaseio.com',
    storageBucket: 'ccclone-1e594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9o6jUCP6AkAPshfbDw0jfG_BJiLostCg',
    appId: '1:953606872243:ios:002a17b1976adcd47524c6',
    messagingSenderId: '953606872243',
    projectId: 'ccclone-1e594',
    databaseURL: 'https://ccclone-1e594-default-rtdb.firebaseio.com',
    storageBucket: 'ccclone-1e594.firebasestorage.app',
    iosBundleId: 'com.example.openSquare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9o6jUCP6AkAPshfbDw0jfG_BJiLostCg',
    appId: '1:953606872243:ios:002a17b1976adcd47524c6',
    messagingSenderId: '953606872243',
    projectId: 'ccclone-1e594',
    databaseURL: 'https://ccclone-1e594-default-rtdb.firebaseio.com',
    storageBucket: 'ccclone-1e594.firebasestorage.app',
    iosBundleId: 'com.example.openSquare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB64QDqucsuqsqV8zz7GyyO1SGruwSNEBE',
    appId: '1:953606872243:web:f300697d507fd9997524c6',
    messagingSenderId: '953606872243',
    projectId: 'ccclone-1e594',
    authDomain: 'ccclone-1e594.firebaseapp.com',
    databaseURL: 'https://ccclone-1e594-default-rtdb.firebaseio.com',
    storageBucket: 'ccclone-1e594.firebasestorage.app',
    measurementId: 'G-5CNXNMYM4N',
  );

}